### PR TITLE
Add Ansible Galaxy release job

### LINKED ISSUE #19: Automate role import into Ansible Galaxy
Currently, it does not seem to automatically import new versions into Ansible galaxy. I would suggest to automate this procedure. According to the documentation of the Ansible Galaxy this could be done via Travis CI.

https://galaxy.ansible.com/docs/contributing/importing.html#import-roles-via-travis-ci

What do you think?

### PR DESCRIPTION
**Pull request by Normo**
This PR adds a CI job to publish this role to [Ansible Galaxy](https://galaxy.ansible.com/ufz/zammad) when a Git tag that match the semantic version format is pushed.
Resolves #19

### CODE REVIEW

**Comment by Normo** [comment]
Test tag has been successfully imported into Galaxy:
tag_imported

**Comment by Normo** [comment]
Hey @christianhueserhzdr, could you please review this PR?

**Comment by christianhueserhzdr** [comment]
> Hey @christianhueserhzdr, could you please review this PR?

Dear Norman @Normo 

nice, that change is very convenient, thanks. It seems to work fine. I will merge this PR.

**Review by christianhueserhzdr — APPROVED** [review]
Your change looks all fine. Thanks.

**Pull request merged**
